require("anvim.plugins.alpha")
require("anvim.plugins.lspconfig")
require("anvim.plugins.lualine")
require("anvim.plugins.nvim-tree")
require("anvim.plugins.telescope")
require("anvim.plugins.toggleterm")
require("anvim.plugins.treesitter")
require("anvim.plugins.which-key")
